import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'package:billify/data/models/business_model.dart';
import 'package:billify/data/models/invoice_model.dart';
import 'package:billify/data/models/ledger_model.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class PdfService {
  static Future<File> generateCustomerLedgerPdf({
    required CustomerLedger ledgerData,
    required List<InvoiceModel> invoices,
    required BusinessModel business,
  }) async {
    final pdf = pw.Document();
    final dateFormat = DateFormat('dd/MM/yyyy');

    pw.MemoryImage? logoImage;
    if (business.business_logo != null && business.business_logo!.isNotEmpty) {
      try {
        String base64Data = business.business_logo!;
        if (base64Data.contains('base64,')) {
          base64Data = base64Data.split('base64,').last;
        }
        final Uint8List logoBytes = base64Decode(base64Data);
        logoImage = pw.MemoryImage(logoBytes);
      } catch (e) {
        print("Error decoding logo: $e");
      }
    }

    // Create a map of invoice ID to items for easy lookup
    final Map<String, List<String>> invoiceItems = {};
    for (var inv in invoices) {
      invoiceItems[inv.id.toUpperCase()] = inv.items.map((i) {
        final qtyStr = i.product.is_weighted
            ? i.quantity.toStringAsFixed(3)
            : i.quantity.toStringAsFixed(0);
        return "${i.name} ($qtyStr ${i.product.uom})";
      }).toList();
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        footer: (context) => pw.Container(
          alignment: pw.Alignment.center,
          margin: const pw.EdgeInsets.only(top: 10),
          child: pw.Text(
            "Generated by Billify - Your Business Companion",
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
          ),
        ),
        build: (context) => [
          // Business Header
          pw.Header(
            level: 0,
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Row(
                  children: [
                    if (logoImage != null)
                      pw.Container(
                        width: 50,
                        height: 50,
                        margin: const pw.EdgeInsets.only(right: 10),
                        child: pw.Image(logoImage),
                      ),
                    pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text(
                          business.name.toUpperCase(),
                          style: pw.TextStyle(
                            fontSize: 24,
                            fontWeight: pw.FontWeight.bold,
                          ),
                        ),
                        if (business.address != null) pw.Text(business.address!),
                        pw.Text("Phone: ${business.phone}"),
                        if (business.gstin != null)
                          pw.Text("GSTIN: ${business.gstin}"),
                      ],
                    ),
                  ],
                ),
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.end,
                  children: [
                    pw.Text("Date: ${dateFormat.format(DateTime.now())}"),
                  ],
                ),
              ],
            ),
          ),

          pw.SizedBox(height: 20),

          // Customer Info & Overall Summary
          pw.Container(
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.grey300),
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      "CUSTOMER DETAILS",
                      style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                    ),
                    pw.Text("Name: ${ledgerData.customer.name}"),
                    pw.Text("Phone: ${ledgerData.customer.phoneNumber}"),
                  ],
                ),
              ],
            ),
          ),

          pw.SizedBox(height: 20),

          // Transactions Table
          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              fontSize: 8,
            ),
            cellStyle: const pw.TextStyle(fontSize: 9),
            columnWidths: {
              0: const pw.FixedColumnWidth(50), // Date
              1: const pw.FixedColumnWidth(60), // Invoice No
              2: const pw.FlexColumnWidth(3), // Items
              3: const pw.FixedColumnWidth(60), // Total Amount
              4: const pw.FixedColumnWidth(50), // You Paid
              5: const pw.FixedColumnWidth(50), // Pending
            },
            headers: [
              'DATE',
              'INVOICE NO',
              'ITEMS',
              'TOTAL AMOUNT',
              'YOU PAID',
              'PENDING',
            ],
            data: List<List<dynamic>>.generate(ledgerData.ledger.length, (
              index,
            ) {
              final entry = ledgerData.ledger[index];
              final dateStr = entry.createdAt != null
                  ? dateFormat.format(entry.createdAt!)
                  : '-';

              String invoiceNo = "-";
              String itemsStr = entry.note ?? "";
              double totalAmount = 0;
              double youPaid = 0;

              if (entry.type == 'credit') {
                totalAmount = entry.amount;
                // If it's an invoice, try to get more details
                if (entry.referenceInvoiceId != null) {
                  final refId = entry.referenceInvoiceId.toString();
                  final matchingInvoice = invoices.where((inv) {
                    final numericPart = inv.id.replaceAll(
                      RegExp(r'[^0-9]'),
                      '',
                    );
                    return int.tryParse(numericPart) == int.tryParse(refId);
                  }).firstOrNull;

                  if (matchingInvoice != null) {
                    invoiceNo = matchingInvoice.id;
                    itemsStr = matchingInvoice.items
                        .map(
                          (i) {
                            final qtyStr = i.product.is_weighted 
                              ? i.quantity.toStringAsFixed(3) 
                              : i.quantity.toStringAsFixed(0);
                            return "${i.name} (${qtyStr} ${i.product.uom})";
                          }
                        )
                        .join(', ');
                    youPaid = matchingInvoice.paid_amount;
                    totalAmount = matchingInvoice.final_amount;
                  }
                }
              } else {
                // It's a payment (Debit)
                invoiceNo = "Payment";
                youPaid = entry.amount;
              }

              final pending = totalAmount - youPaid;

              return [
                dateStr,
                invoiceNo,
                itemsStr,
                totalAmount > 0 ? totalAmount.toStringAsFixed(2) : '-',
                youPaid > 0 ? youPaid.toStringAsFixed(2) : '-',
                pending != 0 ? pending.toStringAsFixed(2) : '0.00',
              ];
            }),
            cellAlignment: pw.Alignment.centerLeft,
            headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
          ),

          pw.SizedBox(height: 20),
          pw.Align(
            alignment: pw.Alignment.centerRight,
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Divider(thickness: 1, color: PdfColors.grey400),
                pw.Text(
                  "OVERALL PENDING AMOUNT: Rs ${ledgerData.summary.remainingBalance.toStringAsFixed(2)}",
                  style: pw.TextStyle(
                    fontSize: 14,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );

    final output = await getTemporaryDirectory();
    final file = File(
      "${output.path}/${ledgerData.customer.name.replaceAll(' ', '_')}.pdf",
    );
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  static Future<File> generateInvoicePdf({
    required InvoiceModel invoice,
  }) async {
    final pdf = pw.Document();
    final dateFormat = DateFormat('dd/MM/yyyy');
    final business = invoice.business;

    pw.MemoryImage? logoImage;
    if (business.business_logo != null && business.business_logo!.isNotEmpty) {
      try {
        String base64Data = business.business_logo!;
        if (base64Data.contains('base64,')) {
          base64Data = base64Data.split('base64,').last;
        }
        final Uint8List logoBytes = base64Decode(base64Data);
        logoImage = pw.MemoryImage(logoBytes);
      } catch (e) {
        print("Error decoding logo: $e");
      }
    }

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.roll80,
        margin: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 10),
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.center,
          children: [
            // ── Business Header ──────────────────────────────────
            if (logoImage != null)
              pw.Container(
                width: 40,
                height: 40,
                margin: const pw.EdgeInsets.only(bottom: 5),
                child: pw.Image(logoImage),
              ),
            pw.Text(
              invoice.business.name.toUpperCase(),
              style: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
                fontSize: 13,
                letterSpacing: 1,
              ),
              textAlign: pw.TextAlign.center,
            ),
            pw.SizedBox(height: 2),
            if (invoice.business.address != null)
              pw.Text(
                invoice.business.address!,
                style: const pw.TextStyle(fontSize: 7),
                textAlign: pw.TextAlign.center,
              ),
            pw.Text(
              "Ph: ${invoice.business.phone}",
              style: const pw.TextStyle(fontSize: 7),
              textAlign: pw.TextAlign.center,
            ),
            if (invoice.business.gstin != null)
              pw.Text(
                "GSTIN: ${invoice.business.gstin}",
                style: const pw.TextStyle(fontSize: 7),
                textAlign: pw.TextAlign.center,
              ),

            pw.SizedBox(height: 4),
            pw.Divider(thickness: 0.8),
            pw.SizedBox(height: 2),

            // ── Invoice Title ─────────────────────────────────────
            pw.Container(
              width: double.infinity,
              child: pw.Text(
                "TAX INVOICE",
                style: pw.TextStyle(
                  fontWeight: pw.FontWeight.bold,
                  fontSize: 9,
                  letterSpacing: 1.5,
                ),
                textAlign: pw.TextAlign.center,
              ),
            ),

            pw.SizedBox(height: 4),
            pw.Divider(thickness: 0.8),
            pw.SizedBox(height: 3),

            // ── Invoice Meta ──────────────────────────────────────
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  "Invoice #: ${invoice.id}",
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 7,
                  ),
                ),
                pw.Text(
                  "Date: ${dateFormat.format(invoice.date)}",
                  style: const pw.TextStyle(fontSize: 7),
                ),
              ],
            ),

            if (invoice.customer_name != null) ...[
              pw.SizedBox(height: 2),
              pw.Row(
                children: [
                  pw.Text(
                    "Bill To: ",
                    style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold,
                      fontSize: 7,
                    ),
                  ),
                  pw.Text(
                    invoice.customer_name!,
                    style: const pw.TextStyle(fontSize: 7),
                  ),
                ],
              ),
            ],

            pw.SizedBox(height: 4),
            pw.Divider(thickness: 0.8),
            pw.SizedBox(height: 2),

            // ── Items Table ───────────────────────────────────────
            pw.TableHelper.fromTextArray(
              border: null,
              headerStyle: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
                fontSize: 7,
              ),
              cellStyle: const pw.TextStyle(fontSize: 7),
              headers: ['Item', 'Qty', 'Price', 'Total'],
              data: invoice.items
                  .map(
                    (i) {
                      final qtyStr = i.product.is_weighted 
                        ? i.quantity.toStringAsFixed(3) 
                        : i.quantity.toStringAsFixed(0);
                      return [
                        i.name,
                        "$qtyStr ${i.product.uom}",
                        "Rs ${i.price.toStringAsFixed(2)}",
                        "Rs ${i.subtotal.toStringAsFixed(2)}",
                      ];
                    }
                  )
                  .toList(),
              cellAlignment: pw.Alignment.centerLeft,
              columnWidths: {
                0: const pw.FlexColumnWidth(3.5),
                1: const pw.FlexColumnWidth(1),
                2: const pw.FlexColumnWidth(1.8),
                3: const pw.FlexColumnWidth(1.8),
              },
              headerDecoration: const pw.BoxDecoration(
                border: pw.Border(
                  bottom: pw.BorderSide(width: 0.8),
                  top: pw.BorderSide(width: 0.8),
                ),
              ),
              oddRowDecoration: const pw.BoxDecoration(),
              cellPadding: const pw.EdgeInsets.symmetric(
                vertical: 2.5,
                horizontal: 1,
              ),
            ),

            pw.SizedBox(height: 3),
            pw.Divider(thickness: 0.8),
            pw.SizedBox(height: 3),

            // ── Totals Section ────────────────────────────────────
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text("Subtotal:", style: const pw.TextStyle(fontSize: 7)),
                pw.Text(
                  "Rs ${invoice.total_amount.toStringAsFixed(2)}",
                  style: const pw.TextStyle(fontSize: 7),
                ),
              ],
            ),

            if (invoice.tax_amount > 0) ...[
              pw.SizedBox(height: 1),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text("Tax:", style: const pw.TextStyle(fontSize: 7)),
                  pw.Text(
                    "Rs ${invoice.tax_amount.toStringAsFixed(2)}",
                    style: const pw.TextStyle(fontSize: 7),
                  ),
                ],
              ),
            ],

            pw.SizedBox(height: 3),
            pw.Container(
              padding: const pw.EdgeInsets.symmetric(vertical: 3),
              decoration: const pw.BoxDecoration(
                border: pw.Border(
                  top: pw.BorderSide(width: 0.8),
                  bottom: pw.BorderSide(width: 0.8),
                ),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(
                    "GRAND TOTAL",
                    style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold,
                      fontSize: 9,
                    ),
                  ),
                  pw.Text(
                    "Rs ${invoice.final_amount.toStringAsFixed(2)}",
                    style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold,
                      fontSize: 9,
                    ),
                  ),
                ],
              ),
            ),

            pw.SizedBox(height: 8),

            // ── Footer ────────────────────────────────────────────
            pw.Text(
              "- Thank You For Your Purchase! -",
              style: pw.TextStyle(fontSize: 7, fontStyle: pw.FontStyle.italic),
              textAlign: pw.TextAlign.center,
            ),
            pw.SizedBox(height: 2),
            pw.Text(
              "Goods once sold will not be taken back.",
              style: const pw.TextStyle(fontSize: 6),
              textAlign: pw.TextAlign.center,
            ),
            pw.SizedBox(height: 6),
          ],
        ),
      ),
    );

    final output = await getTemporaryDirectory();
    final file = File("${output.path}/INV_${invoice.id}.pdf");
    await file.writeAsBytes(await pdf.save());
    return file;
  }
}
